### ISSUE TITLE
Review Page Calendar

### ISSUE THREAD

**Issue by WengerK** [antistatique/windmill#15]
### 💬 Describe the context
A clear and concise description of what the review is about.

#### Utiliser la font Inter (Google Font)

- [x] Voir le bouton Inspecter de Invision

#### Balances des heures

- [x] Aligner Heures et la balance à gauche

> <img width="326" alt="Screenshot 2020-05-27 at 16 22 48" src="https://user-images.githubusercontent.com/1841592/83033483-77191780-a037-11ea-9314-1ffd107d99e9.png">

#### Heures sup dans une case Heure

- [x] Lorsque le total d'un jour est plus grand ou plus petit que les heures standards, afficher l'heure avec la couleur rose

> <img width="360" alt="Screenshot 2020-05-27 at 16 18 48" src="https://user-images.githubusercontent.com/1841592/83032397-10dfc500-a036-11ea-84a0-9a9f9063d6db.png">

#### Ajouter des Tooltips `title` sur les Emoji

- [x] Pour des questions d'accessibilité et de compréhension, ajouter des Title sur les Emoji avec l'explication courte du sigle.

#### Bouton "Justifier les heures" et Emoji "Heures 🤔"

Le bouton "Justifier les heures" et l'Emoji 🤔 ne devraient pas apparaître sur des dates futures.

- [x] Ainsi, lorsque je navigue je devrai voir apparaître le bouton "Justifier les heures" uniquement sur une semaine passée ou en cours.

#### Bouton "Today"

- [x] Il serait vraiment agréable d'avoir un bouton "Aujourd'hui" à côté du bouton "Horaire habituel"

Idée comme Google Calendar

> <img width="544" alt="Screenshot 2020-05-27 at 16 10 13" src="https://user-images.githubusercontent.com/1841592/83031205-95c9df00-a034-11ea-8834-bbb990ad392f.png">

#### Navbar - Element Actif

Définir un style pour l'élément actif de la Navbar

> <img width="897" alt="Screenshot 2020-05-27 at 16 31 51" src="https://user-images.githubusercontent.com/1841592/83033615-9fa11180-a037-11ea-9451-d8597308ca5b.png">

#### Nav Weeks

En début d'année et en fin d'année la navigation en header est broken

> <img width="901" alt="Screenshot 2020-05-27 at 16 35 19" src="https://user-images.githubusercontent.com/1841592/83034405-7fbe1d80-a038-11ea-824d-1ff1a62f4de7.png">

**Comment by JeremyGfeller** [comment]
Hide or show the button `Justifier les heures` and the smiley `🤔` in the commit 0f85b9fb
