### ISSUE TITLE
Review - Ajouter/Diminuer le temps

### ISSUE THREAD

**Issue by WengerK** [antistatique/windmill#16]
### ✅ To modify

Selon le design original, la fonctionalité "Ajouter du temps" et "Diminuer du temps" à quelque peu été revisité par @JeremyGfeller.

> <img width="467" alt="Screenshot 2020-05-27 at 16 25 24" src="https://user-images.githubusercontent.com/1841592/83032984-d6c2f300-a036-11ea-95cb-2cbf758155be.png">

Ceci n'est pas fondamentalement genant, mais il faut revoir la modal pour ressembler un peu plus au Design original. 

> <img width="854" alt="Screenshot 2020-05-27 at 16 25 07" src="https://user-images.githubusercontent.com/1841592/83032991-d9bde380-a036-11ea-97f9-c09595c3213b.png">

#### Améliorer l'affordance des "heures"

- Background gris dans la modal
- Boutons en Blanc
- Selection Rose

**Comment by JeremyGfeller** [comment]
Done in the commit fe8b3943 and 7547c4ce9f
