### ISSUE TITLE
Review - Justification des heures

### ISSUE THREAD

**Issue by WengerK** [antistatique/windmill#17]
### 💬 Describe the context

Selon le design original (https://projects.invisionapp.com/d/main#/console/18397128/382262879/comments)

> <img width="436" alt="Screenshot 2020-05-27 at 16 28 49" src="https://user-images.githubusercontent.com/1841592/83033253-2d303180-a037-11ea-88e5-34fd7e15591f.png">

La modal a été quelque peu remanié par @JeremyGfeller. 

> <img width="661" alt="Screenshot 2020-05-27 at 16 28 51" src="https://user-images.githubusercontent.com/1841592/83033270-315c4f00-a037-11ea-92f8-5308c18624eb.png">

Ceci n'est pas genant. Cependant, il faut veiller à mieux normaliser les 2 modals #16 

#### Harmoniser les 2 modals

Harmoniser le look-&-feel des 2 modals #16 

- Background
- Title
- Bouton de validation

#### Placeholder

Ajouter le placeholder dans le textarea

**Comment by JeremyGfeller** [comment]
Done in the commit fe8b3943 and 7547c4ce9f
