### ISSUE TITLE
Review - Dashboard - affichage du bouton "Horaire habituel"

### ISSUE THREAD

**Issue by nsz** [antistatique/windmill#18]
### 💬 Describe the context
Est-ce utile d'avoir le bouton "horaire habituel" sur la page dashboard ?

### ✅ To modify
List of required modifications:
- [ ] Enlever ce bouton sur cette page :)

### 📸 Screenshots
<img width="1440" alt="Capture d’écran 2020-05-27 à 17 00 41" src="https://user-images.githubusercontent.com/1941982/83037239-d9741700-a03b-11ea-9cec-a9f402679bf3.png">

**Comment by 8uhr** [comment]
il sert à modifier ton horaire habituel à ce que j'ai vu!
Il faudrait juste modifier le label pour que ce soit plus clair :)

**Comment by nsz** [comment]
Oui mais il sert à rien dans le dashboard non ? @8uhr 

Il est utile dans l'écran de saisie :)

**Comment by gido** [comment]
> il sert à modifier ton horaire habituel à ce que j'ai vu!

aahhh, je me demandais justement comment le faire.

Je cherchais une option dans la zone du haut (genre un menu a 3 petits points ou une "roue dentée"
<img width="684" alt="windmill" src="https://user-images.githubusercontent.com/101859/83047889-50fc7300-a049-11ea-9d71-af352e3d628a.png">
