### ISSUE TITLE
Review - indiquer l'onglet actif entre saisie et dashboard

### ISSUE THREAD

**Issue by nsz** [antistatique/windmill#20]
### 💬 Describe the context
Ce serait top de montrer visuellement sur quel onglet on se trouve (saisie ou dashboard)

### ✅ To modify
List of required modifications:
- [x] ajouter un élément sur l'onglet actif

### 📸 Screenshots
<img width="1440" alt="Capture d’écran 2020-05-27 à 17 03 22" src="https://user-images.githubusercontent.com/1941982/83038371-2c020300-a03d-11ea-8acd-897507d90861.png">

**Comment by gido** [comment]
related to #14 ?
