### ISSUE TITLE
Bug - Error message when opening the Dashbord on Chrome 81

### ISSUE THREAD

**Issue by yannlugrin** [antistatique/windmill#22]
### 💬 Describe the bug
When I open the dashboard, after a few seconds an error message is displayed.

Error message in console:
```
Uncaught (in promise) TypeError: Cannot read property '0' of null
    at o.setVar (Dashboard.vue:193)
    at Dashboard.vue:180
```

### 📸 Screenshots
<img width="496" alt="Screenshot 2020-05-27 at 17 14 58" src="https://user-images.githubusercontent.com/9294/83039030-f0b40400-a03d-11ea-8f94-1201a5c36451.png">

### 🖥️ Desktop:
 - OS: OSX 10.14.6
 - Browser Chrome
 - Version 81

**Comment by JeremyGfeller** [comment]
To do: put the email address in `résumé-2020`
