### ISSUE TITLE
Review - Dashboard : Année en cours 2020 : contrôler la valeur

### ISSUE THREAD

**Issue by nsz** [antistatique/windmill#23]
### 💬 Describe the context
La valeur dans "Année en cours 2020" a l'air d'être la colonne M de "résumé 2020" (à prendre 2020) car c'est en jour et la valeur qui est indiquée chez toi a l'air d'être des heures

### ✅ To modify
List of required modifications:
- [x] Vérifier avec @8uhr 
- [x] Changer si nécessaire

### 📸 Screenshots
<img width="665" alt="Capture d’écran 2020-05-27 à 17 16 32" src="https://user-images.githubusercontent.com/1941982/83039113-07f2f180-a03e-11ea-805b-323a40b821b0.png">

<img width="1025" alt="Capture d’écran 2020-05-27 à 17 18 36" src="https://user-images.githubusercontent.com/1941982/83039176-1e994880-a03e-11ea-9a7e-d4684b2fef80.png">

**Comment by 8uhr** [comment]
Effectivement, petite erreur, cela affiche les heures supp totale et non le budget de l'année !
