### ISSUE TITLE
Touch areas on navbar are too small

### ISSUE THREAD

**Issue by nelsonreitz** [antistatique/windmill#25]
### 💬 Is your feature request related to a problem? Please describe.
Les liens de la navigation du bas sont seulement actifs sur la zone des icônes, qui sont très petites, ça demande à l'utilisateur d'être très (trop) précis avec son curseur/son doigt.

### 🧞 Describe the solution you'd like
On pourrait envisager d'agrandir le touch area à l'ensemble de la zone, comme on pourrait rencontrer dans les navigations par tabs sur mobile.
<kbd><img width="502" alt="Capture d’écran 2020-05-27 à 17 30 03" src="https://user-images.githubusercontent.com/10158587/83040593-b8adc080-a03f-11ea-979b-cc6dd35ed7a9.png"></kbd>

**Comment by JeremyGfeller** [comment]
Icons are bigger now. commit 6939a15

**Comment by WengerK** [comment]
The point was to make the whole part clickable, not only the icon
