### ISSUE TITLE
Button hide on small screen

### ISSUE THREAD

**Issue by SuperQuentin** [antistatique/windmill#57]
### 💬 Describe the bug
Button aren't accessible on small screen

### 🔢 To Reproduce
Open the inspecter and reduce screen size

### 🧞 Expected behaviour
Button doesn't keep same format as bigger screen

### 📸 Screenshots
![image](https://user-images.githubusercontent.com/36150436/135989543-3af94951-17f5-4920-aad0-77be1013e9e2.png)

**Comment by RSickenberg** [comment]
Fixed into 204436487b8e9d5d9b39ce727e2b8129522bb966
